import { StyleSheet } from "react-native";

export default StyleSheet.create({
    container: {
        paddingTop: 20,
        paddingBottom: 20,
        paddingLeft: 10,
        paddingRight: 10,
        margin: 5,
        borderRadius: 15,
        backgroundColor: '#DBE2EF',
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        flex: 2,
    },
    text: {
        fontSize: 20,
        fontWeight: 'bold',
    },
    BaseContainer:{
        display: 'flex',
        flexDirection: 'row',
        // justifyContent: 'space-between',
        alignItems: 'center',
    },
    Dangercontainer: {
        paddingTop: 20,
        paddingBottom: 20,
        paddingLeft: 10,
        paddingRight: 10,
        margin: 5,
        borderRadius: 15,
        backgroundColor: '#F56A4D',
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        flex: 2,
    },
    Warningcontainer: {
        paddingTop: 20,
        paddingBottom: 20,
        paddingLeft: 10,
        paddingRight: 10,
        margin: 5,
        borderRadius: 15,
        backgroundColor: '#F9D162',
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        flex: 2,
    },
    deleteButton:{
        fontSize: 28
    },

    // Receipe Styles
    receipeTitle:{
        textAlign: 'center',
        fontSize: 24,
        padding: 10,
        backgroundColor: '#F9D162',
        fontWeight: 'bold',
    },
    receipeView:{
        backgroundColor: 'red',
        padding: 20,
        margin: 10,
        borderRadius: 10,
        backgroundColor: '#CEE6F3',
        marginTop: 30,
    },
    receipeName:{
        fontSize: 20,
        textAlign: 'center',
        borderBottomWidth: .5,
    },
    receipeDescription:{
        fontSize: 16,
        marginTop: 20,
    },
    receipeCloseButton:{
        backgroundColor: '#C51605',
        padding: 10,
        marginRight: 10,
        borderRadius: 10,
    },
    receipeCloseButtonText:{
        fontSize: 22,
        textAlign: 'center',
        color: '#FFF',
        fontWeight: 'bold',
    },
    receipeButtonContainer: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 20,
    },
    receipeButtonRemove:{
        backgroundColor: '#557A46',
        padding: 10,
        marginLeft: 10,
        borderRadius: 10,
    },
    receipeButtonRemoveItem:{
        fontSize: 22,
        textAlign: 'center',
        color: '#FFF',
        fontWeight: 'bold',
    },
})